package com.cell.user.entiy;

import java.util.Date;

public class Role {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.id
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.customer_id
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private String customerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.name
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.description
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.type
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private Byte type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.state
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private Byte state;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.created_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private Date createdTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.created_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private String createdBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.updated_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private Date updatedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.updated_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private String updatedBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.deleted_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private Date deletedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.deleted_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private String deletedBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.deleted
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private Byte deleted;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.datachange_lasttime
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.id
     * @return  the value of role.id
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.id
     * @param id  the value for role.id
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.customer_id
     * @return  the value of role.customer_id
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.customer_id
     * @param customerId  the value for role.customer_id
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.name
     * @return  the value of role.name
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.name
     * @param name  the value for role.name
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.description
     * @return  the value of role.description
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.description
     * @param description  the value for role.description
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.type
     * @return  the value of role.type
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.type
     * @param type  the value for role.type
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.state
     * @return  the value of role.state
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.state
     * @param state  the value for role.state
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.created_time
     * @return  the value of role.created_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.created_time
     * @param createdTime  the value for role.created_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.created_by
     * @return  the value of role.created_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.created_by
     * @param createdBy  the value for role.created_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.updated_time
     * @return  the value of role.updated_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.updated_time
     * @param updatedTime  the value for role.updated_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.updated_by
     * @return  the value of role.updated_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.updated_by
     * @param updatedBy  the value for role.updated_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.deleted_time
     * @return  the value of role.deleted_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public Date getDeletedTime() {
        return deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.deleted_time
     * @param deletedTime  the value for role.deleted_time
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setDeletedTime(Date deletedTime) {
        this.deletedTime = deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.deleted_by
     * @return  the value of role.deleted_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public String getDeletedBy() {
        return deletedBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.deleted_by
     * @param deletedBy  the value for role.deleted_by
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setDeletedBy(String deletedBy) {
        this.deletedBy = deletedBy == null ? null : deletedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.deleted
     * @return  the value of role.deleted
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.deleted
     * @param deleted  the value for role.deleted
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.datachange_lasttime
     * @return  the value of role.datachange_lasttime
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.datachange_lasttime
     * @param datachangeLasttime  the value for role.datachange_lasttime
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}