package com.cell.user.entiy;

public class SysPermission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.id
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.name
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	private String permission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.description
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_permission.display
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	private Boolean display;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.id
	 * @return  the value of sys_permission.id
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.id
	 * @param id  the value for sys_permission.id
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.name
	 * @return  the value of sys_permission.name
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.name
	 * @param name  the value for sys_permission.name
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.permission
	 * @return  the value of sys_permission.permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public String getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.permission
	 * @param permission  the value for sys_permission.permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public void setPermission(String permission) {
		this.permission = permission == null ? null : permission.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.description
	 * @return  the value of sys_permission.description
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.description
	 * @param description  the value for sys_permission.description
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.display
	 * @return  the value of sys_permission.display
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public Boolean getDisplay() {
		return display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.display
	 * @param display  the value for sys_permission.display
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	public void setDisplay(Boolean display) {
		this.display = display;
	}
}