package com.cell.user.mapper;



import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cell.user.entiy.Role;
import com.cell.user.entiy.RoleExample;

public interface RoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     * @mbggenerated  Wed Jan 13 16:59:01 CST 2016
     */
    int updateByPrimaryKey(Role record);
}