package com.cell.user.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cell.user.entiy.SysUser;
import com.cell.user.entiy.SysUserExample;

public interface SysUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int countByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int deleteByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int insertSelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	List<SysUser> selectByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	SysUser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysUser record,
			@Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int updateByExample(@Param("record") SysUser record,
			@Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int updateByPrimaryKey(SysUser record);
}